<!doctype html>
<html lang="id"><head><meta charset="utf-8"><title>Laporan KPI Penjualan</title>
<style>
@page{margin:24px 30px 34px}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:9px;margin:0}.header{width:100%;border-bottom:3px solid #312e81;padding-bottom:12px;margin-bottom:14px}.brand{font-size:10px;font-weight:bold;letter-spacing:1.5px;color:#4f46e5}.title{font-size:22px;font-weight:bold;margin:4px 0 2px}.meta{color:#64748b;font-size:8px}.summary{width:100%;border-spacing:7px 0;margin:0 -7px 17px}.metric{border:1px solid #dbe3ef;background:#f8fafc;padding:10px}.metric-label{font-size:7px;font-weight:bold;color:#64748b;text-transform:uppercase;letter-spacing:.7px}.metric-value{font-size:13px;font-weight:bold;margin-top:5px}.green{color:#047857}.purple{color:#312e81}table.data{width:100%;border-collapse:collapse;table-layout:fixed}table.data th{background:#312e81;color:#fff;text-transform:uppercase;font-size:6.7px;letter-spacing:.35px;padding:8px 6px;text-align:left}table.data td{border:1px solid #dbe3ef;padding:8px 6px;vertical-align:middle;line-height:1.4}table.data tr:nth-child(even) td{background:#f8fafc}.num{text-align:right}.sales{font-weight:bold}.subtle{color:#64748b;font-size:7px;margin-top:2px}.note{white-space:pre-wrap;word-wrap:break-word}.footer{position:fixed;bottom:-22px;left:0;right:0;border-top:1px solid #cbd5e1;padding-top:6px;color:#64748b;font-size:7px}.footer-right{float:right}
</style></head><body>
<div class="header"><div class="brand">UNIFIED CRM</div><div class="title">Laporan KPI Penjualan</div><div class="meta">Periode {{ $periodLabel }} &nbsp;|&nbsp; Diterbitkan {{ now()->translatedFormat('d F Y, H:i') }} WIB</div></div>
<table class="summary"><tr>
<td class="metric"><div class="metric-label">Target Tim</div><div class="metric-value">Rp {{ number_format($summary->target,0,',','.') }}</div></td>
<td class="metric"><div class="metric-label">Realisasi Tim</div><div class="metric-value green">Rp {{ number_format($summary->realization,0,',','.') }}</div></td>
<td class="metric"><div class="metric-label">Pencapaian</div><div class="metric-value purple">{{ number_format($summary->achievement,1,',','.') }}%</div></td>
<td class="metric"><div class="metric-label">Opportunity Closed Won</div><div class="metric-value">{{ number_format($summary->deals) }}</div></td>
</tr></table>
<div style="font-size:11px;font-weight:bold;margin:0 0 6px;color:#312e81">Kinerja Tim</div>
<table class="data"><colgroup><col style="width:15%"><col style="width:10%"><col style="width:12%"><col style="width:4.5%"><col style="width:6.5%"><col style="width:8%"><col style="width:22%"><col style="width:22%"></colgroup>
<thead><tr><th>Head / Sales</th><th class="num">Target</th><th class="num">Realisasi</th><th class="num">Won</th><th class="num">Closing<br>Rate</th><th class="num">Pencapaian</th><th>KPI Operasional (Realisasi / Target)</th><th>Catatan Head / Manager</th></tr></thead><tbody>
@forelse($displayRows as $displayRow)
@if($displayRow->type === 'head')
@php $headRow = $displayRow->data; @endphp
<tr><td class="sales" style="background:#e0e7ff;color:#312e81">{{ $headRow->head->name }}<div class="subtle" style="color:#4f46e5">Head / Koordinator · {{ $headRow->salesCount }} sales</div></td><td class="num" style="background:#e0e7ff;font-weight:bold">Rp {{ number_format($headRow->target,0,',','.') }}</td><td class="num green" style="background:#e0e7ff"><strong>Rp {{ number_format($headRow->realization,0,',','.') }}</strong></td><td class="num" style="background:#e0e7ff;font-weight:bold">{{ $headRow->deals }}</td><td class="num" style="background:#e0e7ff;font-weight:bold">{{ number_format($headRow->closingRate,1,',','.') }}%</td><td class="num purple" style="background:#e0e7ff"><strong>{{ number_format($headRow->achievement,1,',','.') }}%</strong></td><td style="background:#e0e7ff;color:#64748b;text-align:center">—</td><td style="background:#e0e7ff">-</td></tr>
@else
@php $row = $displayRow->data; @endphp
<tr><td class="sales" style="padding-left:16px">{{ $row->sales->name }}<div class="subtle">Sales</div></td><td class="num">Rp {{ number_format((float)($row->target?->sales_target ?? 0),0,',','.') }}</td><td class="num green"><strong>Rp {{ number_format($row->realization,0,',','.') }}</strong></td><td class="num">{{ number_format($row->deals) }}</td><td class="num">{{ number_format($row->closingRate,1,',','.') }}%</td><td class="num purple"><strong>{{ number_format($row->achievement,1,',','.') }}%</strong></td><td><strong>NOO</strong> {{ number_format($row->noo) }}/{{ number_format((int)($row->target?->noo_target ?? 0)) }} &nbsp;·&nbsp; <strong>Custom</strong> {{ number_format($row->customNoo) }}/{{ number_format((int)($row->target?->custom_noo_target ?? 0)) }}<br><strong>Drink</strong> {{ number_format($row->drinkVolume) }}/{{ number_format((int)($row->target?->drink_volume_target ?? 0)) }} &nbsp;·&nbsp; <strong>Food</strong> {{ number_format($row->foodVolume) }}/{{ number_format((int)($row->target?->food_volume_target ?? 0)) }} pcs</td><td class="note">{{ $row->target?->evaluation_notes ?: '-' }}@if(filled($row->target?->evaluation_notes) && $row->target?->updater)<div class="subtle" style="margin-top:4px">By {{ $row->target->updater->name }} · {{ $row->target->updated_at?->translatedFormat('d M Y, H:i') }} WIB</div>@endif</td></tr>
@endif
@empty<tr><td colspan="8" style="text-align:center;padding:20px;color:#64748b">Belum ada data KPI pada periode ini.</td></tr>@endforelse
</tbody></table>
<div class="footer"><span>Dokumen dibuat otomatis oleh Unified CRM. Data mengikuti hak akses pengguna yang mengunduh.</span><span class="footer-right">KPI/{{ $from->format('Ym') }}-{{ $to->format('Ym') }}</span></div>
</body></html>
