<!doctype html><html lang="id"><head><meta charset="utf-8"><title>Laporan KPI Penjualan</title><style>
@page{size:A4 portrait;margin:24px 28px 36px}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#202938;font-size:8px;margin:0}.header{width:100%;border-bottom:2px solid #172033;padding-bottom:12px;margin-bottom:16px}.header td{vertical-align:middle}.logo-box{width:54px;height:54px;border:1px solid #dbe2ea;text-align:center;vertical-align:middle;color:#4f46e5;font-size:18px;font-weight:bold}.company{font-size:15px;font-weight:bold;line-height:1.35}.system{margin-top:4px;color:#697586;font-size:7px;text-transform:uppercase;letter-spacing:1.1px}.classification{text-align:right;color:#697586;font-size:7px;line-height:1.7;letter-spacing:.7px}.report-heading{width:100%;margin-bottom:14px}.report-heading td{vertical-align:bottom}.title{font-size:20px;font-weight:bold;letter-spacing:-.3px}.meta{color:#697586;font-size:7.5px;margin-top:5px}.issued{text-align:right;color:#697586;line-height:1.6}.summary{width:100%;border-spacing:7px 0;margin:0 -7px 18px}.metric{border:1px solid #dce3eb;background:#f8fafc;padding:11px}.metric-label{font-size:6.7px;font-weight:bold;color:#697586;text-transform:uppercase;letter-spacing:.55px}.metric-value{font-size:13px;font-weight:bold;margin-top:5px}.green{color:#047857}.purple{color:#3730a3}.section-title{font-size:10px;font-weight:bold;margin:0 0 7px}table.data{width:100%;border-collapse:collapse;table-layout:fixed}table.data thead{display:table-header-group}table.data tr{page-break-inside:avoid}table.data th{background:#202938;color:#fff;text-transform:uppercase;font-size:6.2px;letter-spacing:.3px;padding:8px 6px;text-align:left}table.data td{border:1px solid #dde3eb;padding:8px 6px;vertical-align:middle;line-height:1.45;word-wrap:break-word}table.data tr.sales-row:nth-child(odd) td{background:#fafbfc}.head-row td{background:#edf1ff!important;border-color:#d7def7!important;font-weight:bold}.num{text-align:right}.sales{font-weight:bold}.subtle{color:#697586;font-size:6.7px;margin-top:3px}.role{text-transform:uppercase;letter-spacing:.45px}.head-meta{color:#4f46e5}.note{white-space:pre-wrap}.empty{color:#98a2b3;text-align:center;padding:18px}.footer{position:fixed;bottom:-22px;left:0;right:0;border-top:1px solid #d6dce5;padding-top:6px;color:#7b8492;font-size:6.5px}.footer-right{float:right}
</style></head><body>
@php
$logoData = null; $logoWidth = 54; $logoHeight = 54;
if ($reportCompany?->logo_path) {
    $logoFile = public_path('storage/'.ltrim($reportCompany->logo_path, '/'));
    if (is_file($logoFile) && is_readable($logoFile)) {
        $logoData = 'data:'.(mime_content_type($logoFile) ?: 'image/png').';base64,'.base64_encode(file_get_contents($logoFile));
        if ($size = getimagesize($logoFile)) {
            [$sourceWidth, $sourceHeight] = $size;
            $scale = min(82 / max(1, $sourceWidth), 50 / max(1, $sourceHeight));
            $logoWidth = max(18, round($sourceWidth * $scale));
            $logoHeight = max(18, round($sourceHeight * $scale));
        }
    }
}
@endphp
<table class="header"><tr><td style="width:{{ $logoData ? $logoWidth + 14 : 68 }}px">@if($logoData)<img src="{{ $logoData }}" width="{{ $logoWidth }}" height="{{ $logoHeight }}" style="display:block">@else<table><tr><td class="logo-box">{{ str($reportCompany?->name ?? 'CRM')->substr(0,1)->upper() }}</td></tr></table>@endif</td><td><div class="company">{{ $reportCompany?->name ?? 'CRM Perusahaan' }}</div><div class="system">Customer Relationship Management</div></td><td class="classification"><strong>SALES PERFORMANCE REPORT</strong><br>Internal use only</td></tr></table>
<table class="report-heading"><tr><td><div class="title">Laporan KPI Penjualan</div><div class="meta">Periode {{ $periodLabel }}</div></td><td class="issued">Diterbitkan<br><strong style="color:#465164">{{ $exportedAt }}</strong></td></tr></table>
<table class="summary"><tr><td class="metric"><div class="metric-label">Target Tim</div><div class="metric-value">Rp {{ number_format($summary->target,0,',','.') }}</div></td><td class="metric"><div class="metric-label">Realisasi Tim</div><div class="metric-value green">Rp {{ number_format($summary->realization,0,',','.') }}</div></td><td class="metric"><div class="metric-label">Pencapaian</div><div class="metric-value purple">{{ number_format($summary->achievement,1,',','.') }}%</div></td><td class="metric"><div class="metric-label">Opportunity Closed Won</div><div class="metric-value">{{ number_format($summary->deals) }}</div></td></tr></table>
<div class="section-title">Kinerja Tim</div><table class="data"><colgroup><col style="width:15%"><col style="width:11%"><col style="width:11%"><col style="width:5%"><col style="width:7%"><col style="width:8%"><col style="width:22%"><col style="width:21%"></colgroup><thead><tr><th>Head / Sales</th><th class="num">Target</th><th class="num">Realisasi</th><th class="num">Won</th><th class="num">Closing Rate</th><th class="num">Pencapaian</th><th>KPI Operasional - Realisasi / Target</th><th>Catatan Head / Manager</th></tr></thead><tbody>
@forelse($displayRows as $displayRow)
@if($displayRow->type === 'head')
@php $headRow = $displayRow->data; @endphp
<tr class="head-row"><td class="sales">{{ $headRow->head->name }}<div class="subtle head-meta">Head / Koordinator</div></td><td class="num">Rp {{ number_format($headRow->target,0,',','.') }}</td><td class="num green">Rp {{ number_format($headRow->realization,0,',','.') }}</td><td class="num">{{ $headRow->deals }}</td><td class="num">{{ number_format($headRow->closingRate,1,',','.') }}%</td><td class="num purple">{{ number_format($headRow->achievement,1,',','.') }}%</td><td class="empty">-</td><td>-</td></tr>
@else
@php
$row = $displayRow->data;
$roleLabel = $row->sales->roles->firstWhere('slug', 'telesales')?->name ?? $row->sales->roles->firstWhere('slug', 'sales')?->name ?? 'Sales';
@endphp
<tr class="sales-row"><td class="sales" style="padding-left:16px">{{ $row->sales->name }}<div class="subtle role">{{ $roleLabel }}</div></td><td class="num">Rp {{ number_format((float)($row->target?->sales_target??0),0,',','.') }}</td><td class="num green"><strong>Rp {{ number_format($row->realization,0,',','.') }}</strong></td><td class="num">{{ number_format($row->deals) }}</td><td class="num">{{ number_format($row->closingRate,1,',','.') }}%</td><td class="num purple"><strong>{{ number_format($row->achievement,1,',','.') }}%</strong></td><td><strong>NOO</strong> {{ number_format($row->noo) }}/{{ number_format((int)($row->target?->noo_target??0)) }} | <strong>Custom</strong> {{ number_format($row->customNoo) }}/{{ number_format((int)($row->target?->custom_noo_target??0)) }} | <strong>Akun Besar</strong> {{ number_format($row->largeAccounts) }}/{{ number_format((int)($row->target?->large_account_target??6)) }}<br><strong>Drink</strong> {{ number_format($row->drinkVolume) }}/{{ number_format((int)($row->target?->drink_volume_target??0)) }} | <strong>Food</strong> {{ number_format($row->foodVolume) }}/{{ number_format((int)($row->target?->food_volume_target??0)) }} pcs</td><td class="note">{{ $row->target?->evaluation_notes?:'-' }}@if(filled($row->target?->evaluation_notes)&&$row->target?->updater)<div class="subtle">{{ $row->target->updater->name }} - {{ $row->target->updated_at?->translatedFormat('d M Y, H:i') }} WIB</div>@endif</td></tr>
@endif
@empty<tr><td colspan="8" class="empty">Belum ada data KPI pada periode ini.</td></tr>@endforelse
</tbody></table><div class="footer"><span>{{ $reportCompany?->name ?? 'CRM Perusahaan' }} - Dokumen internal</span><span class="footer-right">KPI/{{ $from->format('Ym') }}</span></div></body></html>
