@extends('layouts.app')
@section('title','Leads')
@section('eyebrow','CRM / Prospecting')
@section('content')
@php
    $legalNameRequired = \App\Models\SystemSetting::bool('customer_legal_name_required', true, auth()->user());
    $npwpRequired = \App\Models\SystemSetting::bool('customer_npwp_required', true, auth()->user());
@endphp
<div class="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><form class="flex flex-1 gap-2"><input class="field max-w-md" name="search" value="{{ request('search') }}" placeholder="Cari perusahaan, contact, atau lead ID..."><select class="field max-w-44" name="status" onchange="this.form.submit()"><option value="">Semua status</option>@foreach(\App\Models\Lead::EDITABLE_STATUSES as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></form><a href="{{ route('leads.create') }}" class="btn-primary">＋ Lead baru</a></div>
<div class="card overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[980px] text-left"><thead class="table-head"><tr><th class="px-5 py-4">Lead</th><th class="px-4 py-4">Contact</th><th class="px-4 py-4">Source</th><th class="px-4 py-4">Sales</th><th class="px-4 py-4">Follow-up</th><th class="px-4 py-4">Status</th><th class="px-5 py-4"></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($leads as $lead)<tr class="hover:bg-slate-50/70"><td class="px-5 py-4"><div class="text-sm font-extrabold text-ink">{{ $lead->company_name }}</div><div class="mt-1 text-[11px] font-semibold text-slate-400">{{ $lead->lead_id }} @if($lead->brand_name)· {{ $lead->brand_name }}@endif</div></td><td class="px-4 py-4"><div class="text-sm font-semibold">{{ $lead->contact_name }}</div><div class="text-[11px] text-slate-400">{{ $lead->phone }}</div></td><td class="px-4 py-4 text-xs capitalize text-slate-500">{{ str_replace('_',' ',$lead->source) }}</td><td class="px-4 py-4"><div class="text-xs font-bold">{{ $lead->owner->name }}</div></td><td class="px-4 py-4 text-xs {{ $lead->next_follow_up_at?->isPast() ? 'font-bold text-rose-500' : 'text-slate-500' }}">{{ $lead->next_follow_up_at?->format('d M Y, H:i') ?? 'Belum dijadwalkan' }}</td><td class="px-4 py-4"><span class="badge {{ $lead->status === 'converted' ? 'bg-emerald-50 text-emerald-600' : ($lead->status === 'leads_adds' ? 'bg-violet-50 text-violet-700' : (in_array($lead->status, ['leads_hold','leads_risky']) ? 'bg-rose-50 text-rose-600' : 'bg-sky-50 text-sky-600')) }}">{{ $lead->statusLabel() }}</span></td><td class="px-5 py-4 text-right"><div class="flex justify-end gap-2"><a href="{{ route('leads.edit',$lead) }}" class="btn-secondary !px-3 !py-2">Edit</a>@if($lead->status!=='converted')<button type="button" class="btn-primary !px-3 !py-2" onclick="document.getElementById('convert-lead-{{ $lead->id }}').showModal()">Convert</button>@endif</div></td></tr>@empty<tr><td colspan="7" class="p-14 text-center text-sm text-slate-400">Belum ada lead. Tambahkan lead pertama Anda.</td></tr>@endforelse</tbody></table></div></div><div class="mt-5">{{ $leads->links() }}</div>
@foreach($leads as $lead) @if($lead->status!=='converted')
<dialog id="convert-lead-{{ $lead->id }}" class="w-full max-w-lg rounded-2xl p-0 backdrop:bg-slate-950/50">
    <form method="POST" action="{{ route('leads.convert',$lead) }}" enctype="multipart/form-data">@csrf
        <header class="flex items-start justify-between border-b border-slate-100 px-5 py-4"><div><h3 class="text-sm font-extrabold text-ink">Lengkapi data customer</h3><p class="mt-1 text-xs text-slate-500">{{ $lead->company_name }}</p></div><button type="button" onclick="this.closest('dialog').close()" class="grid size-9 place-items-center rounded-full bg-slate-100 text-slate-500">×</button></header>
        <div class="space-y-4 p-5"><div><label class="label">Nama legal{{ $legalNameRequired ? ' *' : ' (opsional)' }}</label><input class="field" name="legal_name" @required($legalNameRequired)></div><div><label class="label">NPWP{{ $npwpRequired ? ' *' : ' (opsional)' }}</label><input class="field" name="npwp" @required($npwpRequired)></div><div><label class="label">Dokumen pendukung</label><input class="field py-2.5" type="file" name="supporting_document" accept=".pdf,.jpg,.jpeg,.png,.webp"><p class="mt-1 text-[10px] text-slate-400">Opsional · maksimal 10 MB</p></div></div>
        <footer class="flex justify-end gap-2 border-t border-slate-100 bg-slate-50 px-5 py-4"><button type="button" onclick="this.closest('dialog').close()" class="btn-secondary">Batal</button><button class="btn-primary">Konversi menjadi customer</button></footer>
    </form>
</dialog>
@endif @endforeach
@endsection
