@extends('layouts.app')
@section('title','KPI Metrics')
@section('eyebrow','Settings / KPI Metrics')
@section('content')
<form method="POST" action="{{ route('settings.kpi-metrics.update') }}" class="mx-auto max-w-5xl space-y-5" x-data="{ metrics:@js($metrics->map(fn($m)=>['id'=>$m->id,'label'=>$m->name,'source'=>$m->source,'enabled'=>$m->is_active,'achievement'=>$m->counts_in_achievement,'threshold'=>$m->threshold,'pipeline_id'=>$m->filters['pipeline_id']??'','product_type'=>$m->filters['product_type']??'','market_segment'=>$m->filters['market_segment']??''])->values()), add(){this.metrics.push({id:null,label:'Metrik baru',source:'won_opportunity',enabled:true,achievement:true,threshold:'',pipeline_id:'',product_type:'',market_segment:''})} }">
@csrf @method('PUT')
<section class="card overflow-hidden">
<header class="flex items-start justify-between border-b border-slate-100 px-5 py-4"><div><h2 class="section-title">Metrik KPI perusahaan</h2><p class="mt-1 text-xs text-slate-500">Atur sumber data serta filter perhitungannya, bukan hanya nama metrik.</p></div><button type="button" class="btn-secondary" @click="add()">＋ Tambah metrik</button></header>
<div class="space-y-4 p-5"><template x-for="(metric,index) in metrics" :key="metric.id || index"><article class="rounded-2xl border border-slate-200 bg-slate-50/60 p-4"><input type="hidden" :name="`metrics[${index}][id]`" :value="metric.id"><div class="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div><label class="label">Nama metrik</label><input class="field mt-1" :name="`metrics[${index}][label]`" x-model="metric.label" required></div><div><label class="label">Diambil dari</label><select class="field mt-1" :name="`metrics[${index}][source]`" x-model="metric.source">@foreach(\App\Models\KpiMetric::SOURCES as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div><div x-show="metric.source === 'large_account'"><label class="label">Minimal nilai</label><input class="field mt-1" type="number" min="0" :name="`metrics[${index}][threshold]`" x-model="metric.threshold"></div><div><label class="label">Pipeline</label><select class="field mt-1" :name="`metrics[${index}][pipeline_id]`" x-model="metric.pipeline_id"><option value="">Semua pipeline</option>@foreach($pipelines as $pipeline)<option value="{{ $pipeline->id }}">{{ $pipeline->name }}</option>@endforeach</select></div><div><label class="label">Jenis produk</label><select class="field mt-1" :name="`metrics[${index}][product_type]`" x-model="metric.product_type"><option value="">Semua jenis</option><option value="regular">Reguler</option><option value="custom">Custom</option></select></div><div><label class="label">Industri produk</label><select class="field mt-1" :name="`metrics[${index}][market_segment]`" x-model="metric.market_segment"><option value="">Semua industri</option><option value="drink">Drink</option><option value="food">Food</option><option value="industry">Industri</option></select></div></div><div class="mt-4 flex items-center justify-between border-t border-slate-200 pt-3 text-xs font-bold text-slate-600"><div class="flex gap-5"><label><input type="hidden" :name="`metrics[${index}][enabled]`" value="0"><input type="checkbox" :name="`metrics[${index}][enabled]`" value="1" x-model="metric.enabled" class="mr-2 accent-brand-600">Aktif</label><label><input type="hidden" :name="`metrics[${index}][achievement]`" value="0"><input type="checkbox" :name="`metrics[${index}][achievement]`" value="1" x-model="metric.achievement" class="mr-2 accent-brand-600">Masuk pencapaian</label></div><button type="button" class="text-rose-600" @click="metrics.splice(index,1)">Hapus</button></div></article></template></div>
</section>
<div class="sticky bottom-4 z-20 flex justify-end rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-lg backdrop-blur"><button class="btn-primary min-w-44 justify-center">Simpan perubahan</button></div>
</form>
@endsection
